// <auto-generated />
using FleetManagementAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetManagementAPI.Migrations.Geofence
{
    [DbContext(typeof(GeofenceContext))]
    partial class GeofenceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FleetManagementAPI.Models.Geofence", b =>
                {
                    b.Property<int>("GeofenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeofenceId"));

                    b.Property<string>("GeofenceArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GeofenceCreateDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GeofenceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GeofenceModifiedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GeofenceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GeofenceVehicles")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GeofenceId");

                    b.ToTable("Geofences");
                });
#pragma warning restore 612, 618
        }
    }
}
