// <auto-generated />
using FleetManagementAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetManagementAPI.Migrations.Trip
{
    [DbContext(typeof(TripContext))]
    [Migration("20241015094405_NinthMigration")]
    partial class NinthMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FleetManagementAPI.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<string>("TripAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripCreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripCreatedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripCustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripDriver")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripEndDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripFromLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripModifiedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripStartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripToLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripTotalDistance")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripTrackingCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TripId");

                    b.ToTable("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
