// <auto-generated />
using FleetManagementAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetManagementAPI.Migrations.TripPayment
{
    [DbContext(typeof(TripPaymentContext))]
    [Migration("20241015094605_TenthMigration")]
    partial class TenthMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FleetManagementAPI.Models.TripPayment", b =>
                {
                    b.Property<int>("TripPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripPaymentId"));

                    b.Property<string>("TripPaymentAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripPaymentCreatedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripPaymentNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripPaymentTripId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripPaymentVehicleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TripPaymentId");

                    b.ToTable("TripPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
