// <auto-generated />
using FleetManagementAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetManagementAPI.Migrations.Vehicle
{
    [DbContext(typeof(VehicleContext))]
    [Migration("20241113135508_EleventhMigration")]
    partial class EleventhMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FleetManagementAPI.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("VehicleChassisNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleCreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleCreatedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleEngineNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleFuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleIsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleManufacturedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleMilagePerLitre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleModifiedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleRegistrationExpiryDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleRegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
