// <auto-generated />
using FleetManagementAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetManagementAPI.Migrations.MoneyFlow
{
    [DbContext(typeof(MoneyFlowContext))]
    partial class MoneyFlowContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FleetManagementAPI.Models.MoneyFlow", b =>
                {
                    b.Property<string>("MoneyFlowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoneyFlowAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoneyFlowCompanyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoneyFlowCreatedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoneyFlowDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoneyFlowDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoneyFlowModifiedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoneyFlowType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MoneyFlowId");

                    b.ToTable("MoneyFlows");
                });
#pragma warning restore 612, 618
        }
    }
}
